# Generated by Django 4.0.4 on 2022-06-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('escolaridade', models.CharField(choices=[('Ensino médio Integrado ao Técnico', 'Ensino médio Integrado ao Técnico'), ('Técnologo', 'Técnologo'), ('Licenciatura', 'Licenciatura'), ('Bacharelado', 'Bacharelado'), ('Pós-Graduaçao', 'Pós-Graduação')], max_length=70, verbose_name='Escolaridade Requerida')),
                ('remuneracao', models.BooleanField(verbose_name='Remunerado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
