# Generated by Django 4.0.4 on 2022-06-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_nome_curso_postagem_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='escolaridade',
            field=models.CharField(choices=[('Ensino médio Integrado ao Técnico', 'Ensino médio Integrado ao Técnico'), ('Técnologo', 'Técnologo'), ('Licenciatura', 'Licenciatura'), ('Bacharelado', 'Bacharelado'), ('Pós-Graduaçao', 'Pós-Graduação')], max_length=70, verbose_name='Escolaridade requerida'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='remuneracao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, verbose_name='Remunerado'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
