# Generated by Django 4.0.4 on 2022-06-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postagem_descricao_alter_postagem_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='remuneradoo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
