# Generated by Django 4.0.4 on 2022-06-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postagem_remuneradoo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='remuneradoo',
        ),
    ]
