# Generated by Django 4.0.4 on 2022-06-29 20:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome Social da Empresa')),
                ('cnpj', models.CharField(max_length=10, null=True, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=11, null=True, verbose_name='Contato')),
                ('rua', models.CharField(max_length=60, null=True, verbose_name='Rua')),
                ('numero', models.CharField(max_length=4, null=True, verbose_name='Numero do Prédio')),
                ('bairro', models.CharField(max_length=120, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
                ('razaosocial', models.CharField(max_length=50, null=True, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
